apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http2-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trafficsim
        protocol: http2
    spec:
      containers:
      - name: http2server
        image: harshals/http2-server:1.3
        ports:
        - containerPort: 8080
